version: '3.8'
services:
  database:
    image: cassandra:latest
    ports:
      - 9042:9042
    container_name: cassandra
    hostname: cassandra
    command: bash -c "docker-entrypoint.sh & until cqlsh -f /scripts/data.cql; do sleep 5; done && tail -f /dev/null"
    environment:
      TZ: Europe/Moscow
    networks:
      - sharenetwork
    # healthcheck:
    #     test: ["CMD", "cqlsh"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
    volumes:
      - type: volume
        source: db-data-lab7
        target: /opt/dse/
      - type: bind
        source: ./src/datamart/src/main/scala/db/data.cql
        target: /scripts/data.cql

volumes:
  db-data-lab7:

networks:
  sharenetwork:
    driver: bridge
